### PR TITLE
Handle 0x7f as KEY_BACKSPACE

### PR DESCRIPTION
**Pull request by rcabaco**
On Mac the backspace key is mapped to DEL (0x7f) and ncurses does not handle it as a special key, which caused the sequence "^?" (stty erase) to be inserted in the text.

From my looking around this seems to be the way to handle this at an application level, that is, to map the DEL as KEY_BACKSPACE.

### CODE REVIEW

**Comment by deadpixi** [comment]
Hi @rcabaco 

Thanks for the PR. Just out of curiosity, does

    MC/?/H/

map the delete key how you want?

**Comment by rcabaco** [comment]
Yes.

Using Alt+Ctrl with ? or H acts like a backspace.

Is there a different way to map the backspace key besides the one I am using?

Is this a more

**Comment by rcabaco** [comment]
Sorry, earlier I did not really understand what you meant with MC/?/H.

I applied the command but it had no effect, this is, Ctrl+? does nothing.

**Comment by deadpixi** [comment]
Hi @rcabaco 

Could you try running that command in tine's command-line?

In other words, do this:

- start tine
- press escape
- type `MC/?/H/`
- see if delete does what you want it to do

Thank you. :)

**Comment by deadpixi** [comment]
Also, what does `echo $TERM` show? Thank you.

**Comment by rcabaco** [comment]
No, the backspace does not work after the command.

$ echo $TERM
xterm

Let me know if you'd like me to do something else.

Thank you.

**Pull request merged**
